### ISSUE TITLE
Residence flags

### ISSUE THREAD

**Issue by Acheron4171** [mb243/NewBlockland#3]
I don't know if it's possible to make residence flags have conditions but if It is, it might be nice to give us the ability to let our claims heal us as long as we haven't taken any damage in, let's say, 20 seconds.

**Comment by mb243** [comment]
There is a flag for that:

https://github.com/mb243/NewBlockland/blob/d8c9e306a60b07e8ef8372ca7ae3ed7236b68bf6/plugins/Residence/flags.yml#L61

https://github.com/Zrips/Residence/wiki/Flag-Default-Settings-and-Behavior

I have it disabled as I think it's an unfair / unbalanced change to gameplay mechanics, and with the focus on being a balanced and challenging environment.

Also noteworthy: There are some flags on there I should probably reevaluate. IMO, `grow`, `iceform`, and `icemelt` at the very least should not be able to be changed by the player.

**Comment by Acheron4171** [comment]
I know that the flag exists I just don't know if it could have the condition applied to it.

**Comment by mb243** [comment]
Oh, gotcha. 

No, it doesn't look like that's possible:

https://github.com/bekvon/Residence/blob/2759d7e81bad48d899af18487c06977cffa4ed14/src/com/bekvon/bukkit/residence/listeners/ResidencePlayerListener.java#L606-L610

**Comment by Acheron4171** [comment]
No worries.
